// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRcKcX_-_FM0nl-1wfA9mW6fbrQf3TNWk',
    appId: '1:238111947770:web:62e24d8f67ccc176f70243',
    messagingSenderId: '238111947770',
    projectId: 'training-firebase-mounir',
    authDomain: 'training-firebase-mounir.firebaseapp.com',
    storageBucket: 'training-firebase-mounir.firebasestorage.app',
    measurementId: 'G-NPT92HSXBX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8KtDVdimwWHKLC-vwSfrPWg7lLC_awLE',
    appId: '1:238111947770:android:8d9f8030c01415c9f70243',
    messagingSenderId: '238111947770',
    projectId: 'training-firebase-mounir',
    storageBucket: 'training-firebase-mounir.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4T72aagYWUXqg-XrYSSkR2wQhqjatCk0',
    appId: '1:238111947770:ios:377c63492f21f8aff70243',
    messagingSenderId: '238111947770',
    projectId: 'training-firebase-mounir',
    storageBucket: 'training-firebase-mounir.firebasestorage.app',
    iosBundleId: 'com.example.trainingFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4T72aagYWUXqg-XrYSSkR2wQhqjatCk0',
    appId: '1:238111947770:ios:377c63492f21f8aff70243',
    messagingSenderId: '238111947770',
    projectId: 'training-firebase-mounir',
    storageBucket: 'training-firebase-mounir.firebasestorage.app',
    iosBundleId: 'com.example.trainingFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRcKcX_-_FM0nl-1wfA9mW6fbrQf3TNWk',
    appId: '1:238111947770:web:0ba65fa7c94b65d9f70243',
    messagingSenderId: '238111947770',
    projectId: 'training-firebase-mounir',
    authDomain: 'training-firebase-mounir.firebaseapp.com',
    storageBucket: 'training-firebase-mounir.firebasestorage.app',
    measurementId: 'G-0KHM9VRQ2K',
  );
}
